FROM node:20-slim AS build

WORKDIR /app/frontend

COPY package.json package-lock.json /app/frontend/
RUN npm ci

COPY . /app/frontend
ARG VITE_SELLER_PORTAL_URL=/seller/
ARG VITE_FF_PORTAL_URL=/
ENV VITE_SELLER_PORTAL_URL=$VITE_SELLER_PORTAL_URL
ENV VITE_FF_PORTAL_URL=$VITE_FF_PORTAL_URL
RUN npm run build


FROM caddy:2-alpine

WORKDIR /srv
COPY --from=build /app/frontend/dist /srv
COPY deploy/Caddyfile.railway /etc/caddy/Caddyfile
