"""Chat models for the seller<->fulfillment messenger (WMS-397/WMS-399).

Minimal contract per owner 2026-09-10:
- Exactly one *main* chat per seller (kind="main"), auto-materialised on first
  read/message. Additional *extra* chats are allowed; participation is explicit
  via ``ChatParticipant``.
- Messages carry text and any number of attachments. An optional attached
  document card is stored as a snapshot on the message row itself, so
  attachments and doc references live next to the message that owns them.
- Access checks are applied at the API layer using existing users/sellers/
  permissions; nothing here creates a second login system.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    func,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.seller import Seller
    from app.models.tenant import Tenant


CHAT_KIND_MAIN = "main"
CHAT_KIND_EXTRA = "extra"
CHAT_KINDS = frozenset({CHAT_KIND_MAIN, CHAT_KIND_EXTRA})


class ChatConversation(Base):
    """One conversation: main (default per seller) or extra.

    ``seller_id`` scopes every conversation — a chat always belongs to exactly
    one seller. For the main chat the unique constraint below guarantees at
    most one row per (tenant, seller). For extra chats there is no uniqueness
    beyond identity — an FF admin can open as many as needed.
    """

    __tablename__ = "chat_conversations"
    __table_args__ = (
        Index(
            "uq_chat_conversations_main",
            "tenant_id",
            "seller_id",
            unique=True,
            postgresql_where=text("kind = 'main'"),
            sqlite_where=text("kind = 'main'"),
        ),
        Index("ix_chat_conversations_seller", "tenant_id", "seller_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    seller_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("sellers.id", ondelete="CASCADE"),
        nullable=False,
    )
    kind: Mapped[str] = mapped_column(String(16), nullable=False)
    title: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    tenant: Mapped[Tenant] = relationship("Tenant")
    seller: Mapped[Seller] = relationship("Seller")


class ChatParticipant(Base):
    """Membership row.

    Main-chat access is implicit for tenant FF users and the owning seller.
    Extra chats require an explicit row for every reader/writer, including
    administrators; main chats do not store participant rows.
    """

    __tablename__ = "chat_participants"
    __table_args__ = (
        UniqueConstraint(
            "conversation_id", "user_id", name="uq_chat_participants_conv_user"
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("chat_conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    added_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    added_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class ChatMessage(Base):
    """A single message.

    ``client_message_id`` is generated by the client and is unique per author
    so that retries after a failed POST don't create duplicates. Attachments
    live in a separate table, attached document card is inlined as JSON.
    """

    __tablename__ = "chat_messages"
    __table_args__ = (
        UniqueConstraint(
            "author_user_id",
            "client_message_id",
            name="uq_chat_messages_author_client_id",
        ),
        Index("ix_chat_messages_conv_created", "conversation_id", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("chat_conversations.id", ondelete="CASCADE"),
        nullable=False,
    )
    author_user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    client_message_id: Mapped[str] = mapped_column(String(64), nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # Attached document reference, if the message was sent from a document.
    # Shape: {"kind": "fbs_order|inbound_intake|marketplace_unload|shipment",
    #         "id": "<uuid>", "title": "...", "seller_id": "<uuid>",
    #         "seller_name": "..."} — snapshot used to render the card.
    attached_document: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    edited_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class ChatAttachment(Base):
    """A single uploaded file, either a normal file or a pasted image.

    ``is_image`` marks payloads that must be rendered inline (paste/Ctrl+V/
    Cmd+V flow). Content lives in the object storage backend under
    ``storage_key``; the API proxies downloads with authorization applied.
    """

    __tablename__ = "chat_attachments"
    __table_args__ = (
        Index("ix_chat_attachments_message", "message_id"),
        Index("ix_chat_attachments_uploader", "tenant_id", "uploader_user_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    uploader_user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("chat_conversations.id", ondelete="CASCADE"),
        nullable=False,
    )
    message_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("chat_messages.id", ondelete="CASCADE"),
        nullable=True,
    )
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    content_type: Mapped[str] = mapped_column(String(128), nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    is_image: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    storage_key: Mapped[str] = mapped_column(String(512), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
