import { useMemo, useState } from 'react'
import { Box, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material'
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'
import { ActionGroup, DataTable, ErrorNotice, FilterBar, IconAction, PrimaryAction, PrintAction, ProductCell, ScreenHeader, SecondaryAction, StatusChip, TextCell } from '../../ui-kit'

type Seller = { id: string; name: string; status: 'Черновик' | 'Требует исправления' | 'Зафиксирован'; liters: string; total: string; problems: number }
type Sku = { id: string; sku: string; vendor: string; volume: string; source: string; liters: string; rate: string; total: string; missing?: boolean }

const initialSellers: Seller[] = [
  { id: 'beauty', name: 'Красотка', status: 'Требует исправления', liters: '12 840,50', total: '8 988,35', problems: 1 },
  { id: 'north', name: 'Норд', status: 'Черновик', liters: '6 432,00', total: '4 502,40', problems: 0 },
  { id: 'vector', name: 'Вектор', status: 'Зафиксирован', liters: '0', total: '0,00', problems: 0 },
]
const initialSkus: Sku[] = [
  { id: '10432', sku: 'SKU-10432', vendor: 'KRS-44-BLK', volume: '2,40', source: 'Ручной обмер', liters: '8 928,00', rate: '0,70', total: '6 249,60' },
  { id: '10433', sku: 'SKU-10433', vendor: 'KRS-44-WHT', volume: '1,18', source: 'Wildberries', liters: '3 912,50', rate: '0,70', total: '2 738,75' },
  { id: '11890', sku: 'SKU-11890', vendor: 'NRD-2XL-LONG', volume: '—', source: 'Неизвестно', liters: '—', rate: '—', total: '—', missing: true },
]

const previousMonth = () => { const d = new Date(); d.setMonth(d.getMonth() - 1); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}` }

export function FfStoragePage({ isFulfillmentAdmin }: { isFulfillmentAdmin: boolean }) {
  const [search, setSearch] = useState(''); const [month, setMonth] = useState(previousMonth())
  const [sellers, setSellers] = useState(initialSellers); const [skus, setSkus] = useState(initialSkus)
  const [expanded, setExpanded] = useState<string | null>('beauty'); const [loading, setLoading] = useState(false)
  const [measureOpen, setMeasureOpen] = useState(false); const [rateOpen, setRateOpen] = useState(false); const [historyOpen, setHistoryOpen] = useState(false); const [printOpen, setPrintOpen] = useState(false)
  const [measureMode, setMeasureMode] = useState<'dimensions' | 'package'>('dimensions'); const [rate, setRate] = useState('0,70')
  const visible = useMemo(() => sellers.filter((s) => !search.trim() || `${s.name} ${s.id}`.toLowerCase().includes(search.trim().toLowerCase()) || (expanded === s.id && skus.some((x) => `${x.sku} ${x.vendor}`.toLowerCase().includes(search.trim().toLowerCase())))), [search, sellers, expanded, skus])
  const missing = skus.some((x) => x.missing); const expandedSeller = sellers.find((x) => x.id === expanded)
  const saveMeasure = () => { setSkus((rows) => rows.map((x) => x.id === '11890' ? { ...x, volume: measureMode === 'package' ? '13,44' : '13,44', source: measureMode === 'package' ? 'Объём тары' : 'Ручной обмер', liters: '4 000,00', rate, total: '2 800,00', missing: false } : x)); setSellers((rows) => rows.map((x) => x.id === 'beauty' ? { ...x, problems: 0, status: 'Черновик' } : x)); setMeasureOpen(false) }
  const fix = () => { if (!isFulfillmentAdmin || missing) return; setSellers((rows) => rows.map((x) => x.id === expanded ? { ...x, status: 'Зафиксирован', problems: 0 } : x)); setPrintOpen(true) }
  return <Box data-testid="ff-storage-page"><ScreenHeader title="Хранение" purpose="Рассчитайте фактическое хранение по селлерам и зафиксируйте месяц для начисления" />
    <FilterBar search={search} onSearchChange={setSearch} searchPlaceholder="Селлер, SKU или артикул продавца" testId="storage-filters"><TextField label="Месяц" type="month" value={month} onChange={(e) => setMonth(e.target.value)} size="small" inputProps={{ 'data-testid': 'storage-month', max: previousMonth() }} /><TextField label="Склад" value="Основной склад" size="small" disabled /></FilterBar>
    <ActionGroup><PrimaryAction data-testid="storage-generate" disabled={loading} onClick={() => { setLoading(true); window.setTimeout(() => setLoading(false), 300) }}>{loading ? 'Формирование…' : 'Сформировать за месяц'}</PrimaryAction>{isFulfillmentAdmin && <SecondaryAction data-testid="storage-rate" onClick={() => setRateOpen(true)}>Изменить тариф</SecondaryAction>}</ActionGroup>
    <Box sx={{ mt: 2 }}><DataTable size="small" columns={[{ key: 'seller', header: 'Селлер', width: 240, render: (r: Seller) => <TextCell>{r.name}</TextCell> }, { key: 'status', header: 'Статус', width: 180, render: (r: Seller) => <StatusChip tone={r.status === 'Зафиксирован' ? 'ok' : r.status === 'Требует исправления' ? 'stop' : 'neutral'}>{r.status}</StatusChip> }, { key: 'liters', header: 'Литро-дни', width: 140, align: 'right', render: (r: Seller) => r.liters }, { key: 'total', header: 'Сумма, ₽', width: 140, align: 'right', render: (r: Seller) => r.total }, { key: 'problems', header: 'Проблемы', width: 110, align: 'right', render: (r: Seller) => r.problems }, { key: 'actions', header: 'Действия', width: 120, align: 'center', render: (r: Seller) => <Stack direction="row"><IconAction title={expanded === r.id ? 'Закрыть расчёт селлера' : 'Открыть расчёт селлера'} onClick={() => setExpanded(expanded === r.id ? null : r.id)} testId={`storage-expand-${r.id}`}><ExpandMoreIcon /></IconAction>{r.status === 'Зафиксирован' && <PrintAction what="накладную" placement="row" onClick={() => setPrintOpen(true)} testId={`storage-print-${r.id}`} />}</Stack> }]} rows={visible} getRowKey={(r) => r.id} empty={{ title: search ? 'Ничего не найдено — измените поиск или фильтры' : 'Тариф хранения ещё не задан', hint: 'Задайте цену за литр-день и дату начала, чтобы сформировать первый расчёт', action: isFulfillmentAdmin ? <PrimaryAction onClick={() => setRateOpen(true)}>Задать тариф</PrimaryAction> : undefined }} testId="storage-seller-table" />
      {expandedSeller && expanded === 'beauty' && <Box sx={{ p: 2, border: '1px solid', borderColor: 'divider' }}><Typography variant="h6">{expandedSeller.name} · {month}</Typography><Typography color="text.secondary">Основной склад · ставка снимка {rate} ₽/л·день</Typography>{missing && <ErrorNotice>Расчёт нельзя зафиксировать: устраните проблемы в строках ниже</ErrorNotice>}<DataTable size="small" columns={[{ key: 'sku', header: 'Товар', width: 150, render: (r: Sku) => <ProductCell>{r.sku}</ProductCell> }, { key: 'vendor', header: 'Артикул продавца', width: 180, render: (r: Sku) => <TextCell>{r.vendor}</TextCell> }, { key: 'volume', header: 'Объём, л', width: 110, align: 'right', render: (r: Sku) => r.volume }, { key: 'source', header: 'Источник', width: 150, render: (r: Sku) => <TextCell>{r.source}</TextCell> }, { key: 'liters', header: 'Литро-дни', width: 130, align: 'right', render: (r: Sku) => r.liters }, { key: 'rate', header: 'Ставка, ₽/л·день', width: 150, align: 'right', render: (r: Sku) => r.rate }, { key: 'total', header: 'Сумма, ₽', width: 120, align: 'right', render: (r: Sku) => r.total }, { key: 'status', header: 'Статус', width: 150, render: (r: Sku) => <StatusChip tone={r.missing ? 'stop' : 'ok'}>{r.missing ? 'Нет габаритов' : 'Рассчитано'}</StatusChip> }, { key: 'actions', header: 'Действия', width: 160, render: (r: Sku) => r.missing ? <PrimaryAction onClick={() => setMeasureOpen(true)}>Внести обмер</PrimaryAction> : <IconAction title="История габаритов" onClick={() => setHistoryOpen(true)}>↻</IconAction> }]} rows={skus} getRowKey={(r) => r.id} testId="storage-sku-table" /></Box>}
    </Box>{expanded === 'beauty' && isFulfillmentAdmin && <ActionGroup><PrimaryAction disabledReason={missing ? 'Нет габаритов у 1 товара' : undefined} onClick={fix} data-testid="storage-fix">Зафиксировать</PrimaryAction></ActionGroup>}
    <Dialog open={measureOpen} onClose={() => setMeasureOpen(false)}><DialogTitle>Внести обмер</DialogTitle><DialogContent><TextField select fullWidth label="Способ" value={measureMode} onChange={(e) => setMeasureMode(e.target.value as 'dimensions' | 'package')}><MenuItem value="dimensions">Габариты товара</MenuItem><MenuItem value="package">Объём тары</MenuItem></TextField><Stack direction="row" spacing={1} sx={{ mt: 2 }}>{measureMode === 'dimensions' ? <><TextField label="Длина, см" defaultValue="40" /><TextField label="Ширина, см" defaultValue="28" /><TextField label="Высота, см" defaultValue="12" /></> : <><TextField label="Объём, л" defaultValue="13,44" /><TextField label="Почему тара" defaultValue="Повреждена упаковка" /></>}</Stack><Typography sx={{ mt: 2 }}>Объём: 13,44 л</Typography></DialogContent><DialogActions><SecondaryAction onClick={() => setMeasureOpen(false)}>Отмена</SecondaryAction><PrimaryAction onClick={saveMeasure}>Сохранить</PrimaryAction></DialogActions></Dialog>
    <Dialog open={rateOpen} onClose={() => setRateOpen(false)}><DialogTitle>Тариф хранения</DialogTitle><DialogContent><Typography>Основной склад</Typography><Stack spacing={2} sx={{ mt: 1 }}><TextField label="Ставка, ₽/л·день" value={rate} onChange={(e) => setRate(e.target.value)} /><TextField label="Дата начала" type="date" defaultValue={`${month}-01`} /></Stack></DialogContent><DialogActions><SecondaryAction onClick={() => setRateOpen(false)}>Отмена</SecondaryAction><PrimaryAction onClick={() => setRateOpen(false)}>Сохранить</PrimaryAction></DialogActions></Dialog>
    <Dialog open={historyOpen} onClose={() => setHistoryOpen(false)}><DialogTitle>История габаритов</DialogTitle><DialogContent><DataTable columns={[{ key: 'date', header: 'Дата', render: () => '18.07.2026' }, { key: 'source', header: 'Источник', render: () => 'Ручной обмер' }, { key: 'value', header: 'Габариты / объём', render: () => '40 × 28 × 12 см · 13,44 л' }, { key: 'author', header: 'Автор', render: () => 'Оператор' }, { key: 'applied', header: 'Применено', render: () => <StatusChip tone="ok">Действует</StatusChip> }]} rows={[{ id: 'current' }]} getRowKey={(r) => r.id} /></DialogContent><DialogActions><SecondaryAction onClick={() => setHistoryOpen(false)}>Закрыть</SecondaryAction>{isFulfillmentAdmin && <PrimaryAction onClick={() => setHistoryOpen(false)}>Вернуть данные WB</PrimaryAction>}</DialogActions></Dialog>
    <Dialog open={printOpen} onClose={() => setPrintOpen(false)}><DialogTitle>Расчёт хранения за {month}</DialogTitle><DialogContent><Typography>Селлер: Красотка</Typography><Typography>Склад: Основной склад</Typography><Typography sx={{ mt: 2, fontWeight: 700 }}>Итого: 11 788,35 ₽</Typography></DialogContent><DialogActions><SecondaryAction onClick={() => setPrintOpen(false)}>Закрыть</SecondaryAction><PrintAction what="накладную" placement="panel" onClick={() => window.print()} /></DialogActions></Dialog>
  </Box>
}
