-- Each SELECT was executed in its own READ ONLY transaction.
-- SET LOCAL statement_timeout = 10s; SET LOCAL lock_timeout = 1s.
-- No FOR UPDATE, write statements, service calls, or CLI dry-run execution.

-- candidate_summary
WITH c AS (SELECT l.*,o.seller_id order_seller_id,o.tenant_id order_tenant_id,o.product_id order_product_id,o.status,o.marketplace,o.supply_id,p.seller_id current_seller_id,p.tenant_id product_tenant_id,u.source supply_source,u.delivered_at FROM fbs_shipment_reversal_ledger l JOIN fbs_orders o ON o.id=l.fbs_order_id JOIN fbs_supplies u ON u.id=o.supply_id JOIN products p ON p.id=l.product_id WHERE p.seller_id IN ('d1f26146-e99a-41af-9471-9c80ec990db3','184f4b05-e623-4746-8edf-c5e408e6d026','a852f30d-bb63-42f9-ac7f-a701ee857cca') AND u.delivered_at IS NOT NULL AND o.status NOT IN ('cancelled','defect') AND l.reversed_at IS NULL AND l.shipment_movement_id IS NULL) SELECT s.name,t.name tenant,count(*) rows,sum(c.quantity) units,min(c.created_at) first_ledger,max(c.created_at) last_ledger,count(*) FILTER(WHERE c.current_seller_id<>c.order_seller_id OR c.tenant_id<>c.order_tenant_id OR c.tenant_id<>c.product_tenant_id OR c.order_product_id IS DISTINCT FROM c.product_id) mismatch,count(*) FILTER(WHERE c.supply_source<>'wms') not_wms,count(*) FILTER(WHERE c.marketplace<>'wb') not_wb,count(*) FILTER(WHERE c.container_id IS NOT NULL) container_rows,md5(string_agg(c.id::text,',' ORDER BY c.id)) candidate_ids_md5 FROM c JOIN sellers s ON s.id=c.current_seller_id JOIN tenants t ON t.id=c.tenant_id GROUP BY s.name,t.name ORDER BY s.name;

-- candidate_sources
WITH c AS (SELECT l.* FROM fbs_shipment_reversal_ledger l JOIN fbs_orders o ON o.id=l.fbs_order_id JOIN fbs_supplies u ON u.id=o.supply_id JOIN products p ON p.id=l.product_id WHERE p.seller_id IN ('d1f26146-e99a-41af-9471-9c80ec990db3','184f4b05-e623-4746-8edf-c5e408e6d026','a852f30d-bb63-42f9-ac7f-a701ee857cca') AND u.delivered_at IS NOT NULL AND o.status NOT IN ('cancelled','defect') AND l.reversed_at IS NULL AND l.shipment_movement_id IS NULL), g AS (SELECT tenant_id,product_id,storage_location_id,container_kind,container_id,sum(quantity) needed FROM c GROUP BY 1,2,3,4,5) SELECT s.name,count(*) source_groups,sum(g.needed) units,sum(coalesce(b.quantity,0)) physical_at_exact_source,count(*) FILTER(WHERE coalesce(b.quantity,0)<g.needed) insufficient_source_groups,sum(greatest(g.needed-coalesce(b.quantity,0),0)) shortage_units,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM inventory_movements m WHERE m.product_id=g.product_id AND m.movement_type='ownership_transfer_out')) products_with_ownership_out FROM g JOIN products p ON p.id=g.product_id JOIN sellers s ON s.id=p.seller_id LEFT JOIN inventory_balances b ON b.tenant_id=g.tenant_id AND b.product_id=g.product_id AND b.storage_location_id=g.storage_location_id AND b.container_kind IS NOT DISTINCT FROM g.container_kind AND b.container_id IS NOT DISTINCT FROM g.container_id GROUP BY s.name ORDER BY s.name;

-- historical_exclusions
SELECT s.name,o.status,CASE WHEN o.supply_id IS NULL THEN 'no_supply_link' WHEN u.delivered_at IS NULL THEN 'not_delivered' ELSE 'delivered' END supply_state,count(*) rows,sum(l.quantity) units FROM fbs_shipment_reversal_ledger l JOIN fbs_orders o ON o.id=l.fbs_order_id JOIN products p ON p.id=l.product_id JOIN sellers s ON s.id=p.seller_id LEFT JOIN fbs_supplies u ON u.id=o.supply_id WHERE p.seller_id IN ('d1f26146-e99a-41af-9471-9c80ec990db3','184f4b05-e623-4746-8edf-c5e408e6d026','a852f30d-bb63-42f9-ac7f-a701ee857cca') AND l.created_at>='2026-08-21' AND l.created_at<'2026-08-27' AND l.shipment_movement_id IS NULL AND l.reversed_at IS NULL GROUP BY 1,2,3 ORDER BY 1,2,3;

-- loviana_order
SELECT o.id,o.wb_order_id,o.status,o.product_id,o.seller_id,s.name seller,p.seller_id current_product_seller,u.wb_supply_id,u.source,u.delivered_at,(SELECT count(*) FROM fbs_shipment_reversal_ledger l WHERE l.fbs_order_id=o.id) ledger_count,(SELECT count(*) FROM fbs_orders x WHERE x.supply_id=o.supply_id) supply_orders,(SELECT count(*) FROM fbs_shipment_reversal_ledger l JOIN fbs_orders x ON x.id=l.fbs_order_id WHERE x.supply_id=o.supply_id AND l.shipment_movement_id IS NOT NULL) supply_linked_movements FROM fbs_orders o JOIN sellers s ON s.id=o.seller_id LEFT JOIN products p ON p.id=o.product_id LEFT JOIN fbs_supplies u ON u.id=o.supply_id WHERE o.id='15272ef2-b423-4f40-95b1-a3fd99e3c821';

-- loviana_movements
SELECT m.id,m.movement_type,m.quantity_delta,m.created_at,m.transfer_group_id,s.name current_product_seller,l.fbs_order_id,o.wb_order_id,CASE WHEN l.shipment_movement_id=m.id THEN 'shipment' WHEN l.reversal_movement_id=m.id THEN 'reversal' END linked_kind FROM inventory_movements m JOIN products p ON p.id=m.product_id LEFT JOIN sellers s ON s.id=p.seller_id LEFT JOIN fbs_shipment_reversal_ledger l ON l.shipment_movement_id=m.id OR l.reversal_movement_id=m.id LEFT JOIN fbs_orders o ON o.id=l.fbs_order_id WHERE m.product_id=(SELECT product_id FROM fbs_orders WHERE id='15272ef2-b423-4f40-95b1-a3fd99e3c821') AND m.created_at>='2026-08-17' AND m.created_at<'2026-08-27' ORDER BY m.created_at;

-- loviana_ownership_pair
SELECT a.quantity_delta source_delta,a.created_at,b.quantity_delta target_delta,ss.name source_seller,ts.name target_seller,a.transfer_group_id,(SELECT sum(quantity) FROM inventory_balances WHERE product_id=a.product_id) current_source_balance,(SELECT sum(quantity) FROM inventory_balances WHERE product_id=b.product_id) current_target_balance FROM inventory_movements a JOIN inventory_movements b ON b.transfer_group_id=a.transfer_group_id AND b.movement_type='ownership_transfer_in' JOIN products sp ON sp.id=a.product_id JOIN sellers ss ON ss.id=sp.seller_id JOIN products tp ON tp.id=b.product_id JOIN sellers ts ON ts.id=tp.seller_id WHERE a.product_id=(SELECT product_id FROM fbs_orders WHERE id='15272ef2-b423-4f40-95b1-a3fd99e3c821') AND a.movement_type='ownership_transfer_out';

-- billing_coverage
SELECT t.name,t.billing_enabled_from,(SELECT count(*) FROM billing_tariff_versions_v2 v WHERE v.tenant_id=t.id AND v.service_code IN ('fbs_order','packing')) all_v2_rates,(SELECT count(*) FROM billing_tariff_versions_v2 v WHERE v.tenant_id=t.id AND v.service_code IN ('fbs_order','packing') AND v.enabled AND v.valid_from_at<'2026-09-09' AND (v.valid_to_at IS NULL OR v.valid_to_at>='2026-08-01')) enabled_v2_rates_overlapping_aug_sep,(SELECT count(*) FROM billing_tariff_versions v WHERE v.tenant_id=t.id AND v.service_code IN ('fbs_order','packing')) legacy_rates FROM tenants t WHERE t.id='7b98a8aa-c03c-4649-9677-a645be45c622';

-- billing_order_scope
SELECT s.name,o.status,count(*) orders,count(*) FILTER(WHERE u.delivered_at IS NOT NULL) with_handover,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM operation_facts f WHERE f.tenant_id=o.tenant_id AND f.document_type='fbs_order' AND f.document_id=o.id)) with_fact,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM billing_ledger_entries e WHERE e.tenant_id=o.tenant_id AND e.source_type='fbs_order' AND e.source_id=o.id AND e.service_code='fbs_order')) with_fbs_charge,min(coalesce(u.delivered_at,o.packed_at,o.picked_at,o.created_at_wb)) first_work_candidate,max(coalesce(u.delivered_at,o.packed_at,o.picked_at,o.created_at_wb)) last_work_candidate FROM fbs_orders o JOIN sellers s ON s.id=o.seller_id LEFT JOIN fbs_supplies u ON u.id=o.supply_id WHERE o.tenant_id='7b98a8aa-c03c-4649-9677-a645be45c622' AND o.marketplace='wb' AND (s.id IN ('d1f26146-e99a-41af-9471-9c80ec990db3','bf8eea6b-eaa6-47ea-8dfc-289142372dab') OR s.id=(SELECT seller_id FROM fbs_orders WHERE id='15272ef2-b423-4f40-95b1-a3fd99e3c821')) AND o.created_at_wb<'2026-09-05' GROUP BY 1,2 ORDER BY 1,2;

-- mashnin_negative
SELECT p.id product_id,l.storage_location_id,count(*) candidate_orders,sum(l.quantity) candidate_units,b.quantity current_physical,b.quantity-sum(l.quantity) after_proposed_writeoff FROM fbs_shipment_reversal_ledger l JOIN fbs_orders o ON o.id=l.fbs_order_id JOIN fbs_supplies u ON u.id=o.supply_id JOIN products p ON p.id=l.product_id LEFT JOIN inventory_balances b ON b.tenant_id=l.tenant_id AND b.product_id=l.product_id AND b.storage_location_id=l.storage_location_id AND b.container_kind IS NOT DISTINCT FROM l.container_kind AND b.container_id IS NOT DISTINCT FROM l.container_id WHERE p.seller_id='184f4b05-e623-4746-8edf-c5e408e6d026' AND u.delivered_at IS NOT NULL AND o.status NOT IN ('cancelled','defect') AND l.reversed_at IS NULL AND l.shipment_movement_id IS NULL GROUP BY p.id,l.storage_location_id,b.quantity HAVING coalesce(b.quantity,0)<sum(l.quantity);

-- loviana_pick
SELECT p.fbs_order_id,o.wb_order_id,p.picked_at,p.undone_at,p.inventory_movement_id FROM fbs_order_picks p JOIN fbs_orders o ON o.id=p.fbs_order_id WHERE p.inventory_movement_id='947b0124-85a4-42a8-be50-f10f0cfec587' OR p.fbs_order_id='15272ef2-b423-4f40-95b1-a3fd99e3c821';

-- billing_cancel_evidence
SELECT s.name,o.status,count(*) orders,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM document_event e WHERE e.tenant_id=o.tenant_id AND e.document_type='fbs_order' AND e.document_id=o.id AND e.event_type='status_changed')) with_status_history,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM document_event e WHERE e.tenant_id=o.tenant_id AND e.document_type='fbs_order' AND e.document_id=o.id AND e.event_type='status_changed' AND (e.payload_json->>'status_after' IN ('sorted','done') OR e.payload_json->>'status_before' IN ('sorted','done')))) sorted_done_history,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM fbs_shipment_reversal_ledger l WHERE l.fbs_order_id=o.id AND l.shipment_movement_id IS NOT NULL)) with_shipment_link FROM fbs_orders o JOIN sellers s ON s.id=o.seller_id WHERE o.tenant_id='7b98a8aa-c03c-4649-9677-a645be45c622' AND o.marketplace='wb' AND o.seller_id IN ('d1f26146-e99a-41af-9471-9c80ec990db3','bf8eea6b-eaa6-47ea-8dfc-289142372dab','9819f2c6-b28e-401e-a163-6ffe9e420da6') AND o.created_at_wb<'2026-09-05' AND o.status IN ('cancelled','defect') GROUP BY 1,2 ORDER BY 1,2;

-- billing_date_readiness
WITH c AS (SELECT o.id,o.tenant_id,s.name,coalesce(u.delivered_at,o.packed_at,o.picked_at,o.created_at_wb) moment,CASE WHEN u.delivered_at IS NOT NULL THEN 'handover' WHEN o.packed_at IS NOT NULL THEN 'packed' WHEN o.picked_at IS NOT NULL THEN 'picked' ELSE 'wb_created_fallback' END date_source,f.id fact_id,f.occurred_at fact_at FROM fbs_orders o JOIN sellers s ON s.id=o.seller_id LEFT JOIN fbs_supplies u ON u.id=o.supply_id LEFT JOIN operation_facts f ON f.tenant_id=o.tenant_id AND f.document_type='fbs_order' AND f.document_id=o.id WHERE o.tenant_id='7b98a8aa-c03c-4649-9677-a645be45c622' AND o.marketplace='wb' AND o.seller_id IN ('d1f26146-e99a-41af-9471-9c80ec990db3','bf8eea6b-eaa6-47ea-8dfc-289142372dab','9819f2c6-b28e-401e-a163-6ffe9e420da6') AND o.created_at_wb<'2026-09-05' AND (o.status IN ('sorted','done') OR (o.status='in_delivery' AND u.delivered_at IS NOT NULL))) SELECT name,date_source,count(*) orders,count(*) FILTER(WHERE fact_id IS NULL) missing_facts,count(*) FILTER(WHERE abs(extract(epoch from (fact_at-moment)))>86400) date_drift_over_day,count(*) FILTER(WHERE abs(extract(epoch from (fact_at-moment)))>86400 AND (EXISTS(SELECT 1 FROM billing_ledger_entries b WHERE b.tenant_id=c.tenant_id AND b.source_type='fbs_order' AND b.source_id=c.id) OR EXISTS(SELECT 1 FROM billing_invoice_v2_sources z WHERE z.tenant_id=c.tenant_id AND z.operation_fact_id=c.fact_id))) drift_protected_by_money FROM c GROUP BY 1,2 ORDER BY 1,2;

-- loviana_all_shipment_links
SELECT m.id,m.quantity_delta,m.created_at,o.wb_order_id FROM inventory_movements m LEFT JOIN fbs_shipment_reversal_ledger l ON l.shipment_movement_id=m.id OR l.reversal_movement_id=m.id LEFT JOIN fbs_orders o ON o.id=l.fbs_order_id WHERE m.product_id='eadd0460-4850-4a39-a7f4-7758e14c9f42' AND m.movement_type='fbs_shipment' ORDER BY m.created_at;
