-- WMS-501 authorized production audit: aggregate counts only; no changes.
-- Each check is bounded separately and a timeout is retained as incomplete, not retried.
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_invoice_v2_idempotency.user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_invoice_v2_idempotency" c JOIN "users" p ON p."id"=c."user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_invoices.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_invoices" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_invoices_v2.issued_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_invoices_v2" c JOIN "users" p ON p."id"=c."issued_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_invoices_v2.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_invoices_v2" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_entries.performer_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_entries" c JOIN "users" p ON p."id"=c."performer_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_entries.reversal_of_id->billing_ledger_entries.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_entries" c JOIN "billing_ledger_entries" p ON p."id"=c."reversal_of_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_entries.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_entries" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_entries.tariff_version_id->billing_tariff_versions.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_entries" c JOIN "billing_tariff_versions" p ON p."id"=c."tariff_version_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_entries.tariff_version_v2_id->billing_tariff_versions_v2.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_entries" c JOIN "billing_tariff_versions_v2" p ON p."id"=c."tariff_version_v2_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_entries.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_entries" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_lines.ledger_entry_id->billing_ledger_entries.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_lines" c JOIN "billing_ledger_entries" p ON p."id"=c."ledger_entry_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_lines.operation_fact_line_id->operation_fact_lines.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_lines" c JOIN "operation_fact_lines" p ON p."id"=c."operation_fact_line_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_lines.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_lines" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_ledger_lines.tariff_version_v2_id->billing_tariff_versions_v2.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_ledger_lines" c JOIN "billing_tariff_versions_v2" p ON p."id"=c."tariff_version_v2_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_profiles.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_profiles" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_run_issues.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_run_issues" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_tariff_service_states.config_id->billing_tariff_matrix_configs.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_tariff_service_states" c JOIN "billing_tariff_matrix_configs" p ON p."id"=c."config_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_tariff_versions.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_tariff_versions" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_tariff_versions.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_tariff_versions" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_tariff_versions_v2.employee_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_tariff_versions_v2" c JOIN "users" p ON p."id"=c."employee_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_tariff_versions_v2.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_tariff_versions_v2" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'billing_tariff_versions_v2.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "billing_tariff_versions_v2" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'discrepancy_acts.inbound_intake_request_id->inbound_intake_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "discrepancy_acts" c JOIN "inbound_intake_requests" p ON p."id"=c."inbound_intake_request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'discrepancy_acts.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "discrepancy_acts" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'document_event.actor_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "document_event" c JOIN "users" p ON p."id"=c."actor_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'document_event.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "document_event" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_binding_stock_pools.binding_id->fbs_warehouse_bindings.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_binding_stock_pools" c JOIN "fbs_warehouse_bindings" p ON p."id"=c."binding_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_binding_stock_pools.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_binding_stock_pools" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_binding_stock_pools.updated_by->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_binding_stock_pools" c JOIN "users" p ON p."id"=c."updated_by";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_markings.created_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_markings" c JOIN "users" p ON p."id"=c."created_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_markings.marking_code_id->marking_codes.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_markings" c JOIN "marking_codes" p ON p."id"=c."marking_code_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_markings.order_id->fbs_orders.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_markings" c JOIN "fbs_orders" p ON p."id"=c."order_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_picks.fbs_order_id->fbs_orders.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_picks" c JOIN "fbs_orders" p ON p."id"=c."fbs_order_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_picks.fbs_supply_id->fbs_supplies.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_picks" c JOIN "fbs_supplies" p ON p."id"=c."fbs_supply_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_picks.inventory_movement_id->inventory_movements.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_picks" c JOIN "inventory_movements" p ON p."id"=c."inventory_movement_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_picks.picked_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_picks" c JOIN "users" p ON p."id"=c."picked_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_picks.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_picks" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_picks.sorting_storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_picks" c JOIN "storage_locations" p ON p."id"=c."sorting_storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_picks.source_storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_picks" c JOIN "storage_locations" p ON p."id"=c."source_storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_picks.fbs_supply_id->fbs_supplies.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_picks" c JOIN "fbs_supplies" p ON p."id"=c."fbs_supply_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_picks.inventory_movement_id->inventory_movements.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_picks" c JOIN "inventory_movements" p ON p."id"=c."inventory_movement_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_picks.picked_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_picks" c JOIN "users" p ON p."id"=c."picked_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_picks.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_picks" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_picks.sorting_storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_picks" c JOIN "storage_locations" p ON p."id"=c."sorting_storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_picks.source_storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_picks" c JOIN "storage_locations" p ON p."id"=c."source_storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_picks.undone_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_picks" c JOIN "users" p ON p."id"=c."undone_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_reservations.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_reservations" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_product_reservations.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_product_reservations" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_reservations.fbs_order_id->fbs_orders.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_reservations" c JOIN "fbs_orders" p ON p."id"=c."fbs_order_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_reservations.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_reservations" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_order_reservations.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_order_reservations" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_orders.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_orders" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_orders.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_orders" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_orders.supply_id->fbs_supplies.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_orders" c JOIN "fbs_supplies" p ON p."id"=c."supply_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_orders.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_orders" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packaging_fulfillments.fbs_order_id->fbs_orders.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packaging_fulfillments" c JOIN "fbs_orders" p ON p."id"=c."fbs_order_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packaging_fulfillments.fulfilled_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packaging_fulfillments" c JOIN "users" p ON p."id"=c."fulfilled_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packaging_fulfillments.inventory_movement_id->inventory_movements.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packaging_fulfillments" c JOIN "inventory_movements" p ON p."id"=c."inventory_movement_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packaging_fulfillments.packaging_task_id->packaging_tasks.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packaging_fulfillments" c JOIN "packaging_tasks" p ON p."id"=c."packaging_task_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packing_box_items.assigned_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packing_box_items" c JOIN "users" p ON p."id"=c."assigned_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packing_box_items.box_id->fbs_packing_boxes.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packing_box_items" c JOIN "fbs_packing_boxes" p ON p."id"=c."box_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packing_box_items.fbs_order_id->fbs_orders.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packing_box_items" c JOIN "fbs_orders" p ON p."id"=c."fbs_order_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packing_boxes.supply_id->fbs_supplies.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packing_boxes" c JOIN "fbs_supplies" p ON p."id"=c."supply_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_packing_boxes.warehouse_box_id->warehouse_boxes.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_packing_boxes" c JOIN "warehouse_boxes" p ON p."id"=c."warehouse_box_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_print_assets.applied_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_print_assets" c JOIN "users" p ON p."id"=c."applied_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_print_assets.fbs_order_id->fbs_orders.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_print_assets" c JOIN "fbs_orders" p ON p."id"=c."fbs_order_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_print_assets.fbs_supply_id->fbs_supplies.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_print_assets" c JOIN "fbs_supplies" p ON p."id"=c."fbs_supply_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_print_assets.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_print_assets" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_shipment_reversal_ledger.fbs_order_id->fbs_orders.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_shipment_reversal_ledger" c JOIN "fbs_orders" p ON p."id"=c."fbs_order_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_shipment_reversal_ledger.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_shipment_reversal_ledger" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_shipment_reversal_ledger.reversal_movement_id->inventory_movements.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_shipment_reversal_ledger" c JOIN "inventory_movements" p ON p."id"=c."reversal_movement_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_shipment_reversal_ledger.shipment_movement_id->inventory_movements.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_shipment_reversal_ledger" c JOIN "inventory_movements" p ON p."id"=c."shipment_movement_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_shipment_reversal_ledger.source_warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_shipment_reversal_ledger" c JOIN "warehouses" p ON p."id"=c."source_warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_shipment_reversal_ledger.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_shipment_reversal_ledger" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_shipment_reversal_ledger.wb_operation_id->fbs_wb_operations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_shipment_reversal_ledger" c JOIN "fbs_wb_operations" p ON p."id"=c."wb_operation_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_shipment_reversal_ledger.written_off_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_shipment_reversal_ledger" c JOIN "users" p ON p."id"=c."written_off_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_supplies.barcode_asset_id->fbs_print_assets.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_supplies" c JOIN "fbs_print_assets" p ON p."id"=c."barcode_asset_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_supplies.boxes_without_distribution_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_supplies" c JOIN "users" p ON p."id"=c."boxes_without_distribution_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_supplies.honest_sign_skipped_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_supplies" c JOIN "users" p ON p."id"=c."honest_sign_skipped_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_supplies.operator_finished_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_supplies" c JOIN "users" p ON p."id"=c."operator_finished_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_supplies.packaging_task_id->packaging_tasks.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_supplies" c JOIN "packaging_tasks" p ON p."id"=c."packaging_task_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_supplies.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_supplies" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_supplies.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_supplies" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_warehouse_bindings.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_warehouse_bindings" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_warehouse_bindings.wms_warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_warehouse_bindings" c JOIN "warehouses" p ON p."id"=c."wms_warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_wb_operations.created_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_wb_operations" c JOIN "users" p ON p."id"=c."created_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'fbs_wb_operations.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "fbs_wb_operations" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_boxes.pallet_id->pallets.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_boxes" c JOIN "pallets" p ON p."id"=c."pallet_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_boxes.request_id->inbound_intake_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_boxes" c JOIN "inbound_intake_requests" p ON p."id"=c."request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_boxes.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_boxes" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_cargo_place_lines.cargo_place_id->inbound_intake_cargo_places.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_cargo_place_lines" c JOIN "inbound_intake_cargo_places" p ON p."id"=c."cargo_place_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_cargo_place_lines.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_cargo_place_lines" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_cargo_places.pallet_id->pallets.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_cargo_places" c JOIN "pallets" p ON p."id"=c."pallet_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_cargo_places.request_id->inbound_intake_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_cargo_places" c JOIN "inbound_intake_requests" p ON p."id"=c."request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_cargo_places.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_cargo_places" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_requests.completed_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_requests" c JOIN "users" p ON p."id"=c."completed_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_requests.created_by_seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_requests" c JOIN "sellers" p ON p."id"=c."created_by_seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_requests.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_requests" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_requests.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_requests" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_ozon_return_giveouts.request_id->inbound_intake_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_ozon_return_giveouts" c JOIN "inbound_intake_requests" p ON p."id"=c."request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_ozon_return_items.giveout_record_id->inbound_ozon_return_giveouts.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_ozon_return_items" c JOIN "inbound_ozon_return_giveouts" p ON p."id"=c."giveout_record_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_ozon_return_items.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_ozon_return_items" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_ozon_return_items.request_id->inbound_intake_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_ozon_return_items" c JOIN "inbound_intake_requests" p ON p."id"=c."request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_balances.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_balances" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_balances.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_balances" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_count_created_containers.count_id->inventory_counts.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_count_created_containers" c JOIN "inventory_counts" p ON p."id"=c."count_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_count_found_scans.count_id->inventory_counts.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_count_found_scans" c JOIN "inventory_counts" p ON p."id"=c."count_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_counts.created_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_counts" c JOIN "users" p ON p."id"=c."created_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_counts.posted_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_counts" c JOIN "users" p ON p."id"=c."posted_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_counts.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_counts" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_counts.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_counts" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_movements.actor_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_movements" c JOIN "users" p ON p."id"=c."actor_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_movements.marketplace_unload_request_id->marketplace_unload_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_movements" c JOIN "marketplace_unload_requests" p ON p."id"=c."marketplace_unload_request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_movements.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_movements" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_movements.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_movements" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_movements.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_movements" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_movements.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_movements" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_reservations.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_reservations" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_reservations.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_reservations" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_reservations.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_reservations" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'kiz_reprints.created_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "kiz_reprints" c JOIN "users" p ON p."id"=c."created_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'kiz_reprints.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "kiz_reprints" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_accounts.created_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_accounts" c JOIN "users" p ON p."id"=c."created_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_accounts.disconnected_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_accounts" c JOIN "users" p ON p."id"=c."disconnected_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_accounts.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_accounts" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_accounts.updated_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_accounts" c JOIN "users" p ON p."id"=c."updated_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_unload_requests.cancelled_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_unload_requests" c JOIN "users" p ON p."id"=c."cancelled_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_unload_requests.completed_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_unload_requests" c JOIN "users" p ON p."id"=c."completed_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_unload_requests.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_unload_requests" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_unload_requests.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_unload_requests" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_unload_reservations.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_unload_reservations" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_unload_reservations.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_unload_reservations" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_events.actor_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_events" c JOIN "users" p ON p."id"=c."actor_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_events.code_id->marking_codes.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_events" c JOIN "marking_codes" p ON p."id"=c."code_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_events.packaging_task_id->packaging_tasks.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_events" c JOIN "packaging_tasks" p ON p."id"=c."packaging_task_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_events.pool_id->marking_pools.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_events" c JOIN "marking_pools" p ON p."id"=c."pool_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_events.print_batch_id->marking_print_batches.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_events" c JOIN "marking_print_batches" p ON p."id"=c."print_batch_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_events.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_events" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_import_files.import_batch_id->marking_code_imports.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_import_files" c JOIN "marking_code_imports" p ON p."id"=c."import_batch_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_imports.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_imports" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_code_imports.uploaded_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_code_imports" c JOIN "users" p ON p."id"=c."uploaded_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_codes.import_batch_id->marking_code_imports.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_codes" c JOIN "marking_code_imports" p ON p."id"=c."import_batch_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_codes.pool_id->marking_pools.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_codes" c JOIN "marking_pools" p ON p."id"=c."pool_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_codes.printed_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_codes" c JOIN "users" p ON p."id"=c."printed_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_codes.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_codes" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_codes.replaced_by_code_id->marking_codes.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_codes" c JOIN "marking_codes" p ON p."id"=c."replaced_by_code_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_codes.reserved_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_codes" c JOIN "users" p ON p."id"=c."reserved_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_codes.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_codes" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_pool_products.pool_id->marking_pools.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_pool_products" c JOIN "marking_pools" p ON p."id"=c."pool_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_pool_products.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_pool_products" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_pools.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_pools" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_print_batches.created_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_print_batches" c JOIN "users" p ON p."id"=c."created_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_print_batches.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_print_batches" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_print_batches.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_print_batches" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_reprint_requests.code_id->marking_codes.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_reprint_requests" c JOIN "marking_codes" p ON p."id"=c."code_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_reprint_requests.requested_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_reprint_requests" c JOIN "users" p ON p."id"=c."requested_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marking_reprint_requests.resolved_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marking_reprint_requests" c JOIN "users" p ON p."id"=c."resolved_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'operation_fact_lines.operation_fact_id->operation_facts.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "operation_fact_lines" c JOIN "operation_facts" p ON p."id"=c."operation_fact_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'operation_fact_lines.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "operation_fact_lines" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'operation_facts.actor_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "operation_facts" c JOIN "users" p ON p."id"=c."actor_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'operation_facts.reversal_of_id->operation_facts.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "operation_facts" c JOIN "operation_facts" p ON p."id"=c."reversal_of_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'operation_facts.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "operation_facts" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'operation_facts.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "operation_facts" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'outbound_shipment_requests.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "outbound_shipment_requests" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'outbound_shipment_requests.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "outbound_shipment_requests" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_task_events.created_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_task_events" c JOIN "users" p ON p."id"=c."created_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_task_events.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_task_events" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_task_events.reversed_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_task_events" c JOIN "users" p ON p."id"=c."reversed_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_task_events.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_task_events" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_task_events.task_id->packaging_tasks.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_task_events" c JOIN "packaging_tasks" p ON p."id"=c."task_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_tasks.completed_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_tasks" c JOIN "users" p ON p."id"=c."completed_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_tasks.created_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_tasks" c JOIN "users" p ON p."id"=c."created_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_tasks.inbound_intake_request_id->inbound_intake_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_tasks" c JOIN "inbound_intake_requests" p ON p."id"=c."inbound_intake_request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_tasks.marketplace_unload_request_id->marketplace_unload_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_tasks" c JOIN "marketplace_unload_requests" p ON p."id"=c."marketplace_unload_request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_tasks.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_tasks" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'pallets.inbound_request_id->inbound_intake_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "pallets" c JOIN "inbound_intake_requests" p ON p."id"=c."inbound_request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'pallets.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "pallets" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'pallets.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "pallets" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'print_connections.paired_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "print_connections" c JOIN "users" p ON p."id"=c."paired_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'print_connections.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "print_connections" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'print_templates.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "print_templates" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'print_templates.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "print_templates" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'print_templates.user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "print_templates" c JOIN "users" p ON p."id"=c."user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'product_dimension_events.author_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "product_dimension_events" c JOIN "users" p ON p."id"=c."author_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'product_dimension_events.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "product_dimension_events" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'product_marketplace_links.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "product_marketplace_links" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'product_marketplace_links.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "product_marketplace_links" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'product_tz_imports.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "product_tz_imports" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'product_tz_imports.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "product_tz_imports" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'products.dimensions_updated_by_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "products" c JOIN "users" p ON p."id"=c."dimensions_updated_by_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'products.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "products" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'seller_marking_credentials.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "seller_marking_credentials" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'seller_wildberries_imported_cards.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "seller_wildberries_imported_cards" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'seller_wildberries_imported_supplies.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "seller_wildberries_imported_supplies" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'stock_directions.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "stock_directions" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'stock_monthly_snapshots.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "stock_monthly_snapshots" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_locations.rack_id->warehouse_storage_racks.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_locations" c JOIN "warehouse_storage_racks" p ON p."id"=c."rack_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_locations.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_locations" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_measurements.dimension_event_id->product_dimension_events.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_measurements" c JOIN "product_dimension_events" p ON p."id"=c."dimension_event_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_measurements.movement_end_id->inventory_movements.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_measurements" c JOIN "inventory_movements" p ON p."id"=c."movement_end_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_measurements.movement_start_id->inventory_movements.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_measurements" c JOIN "inventory_movements" p ON p."id"=c."movement_start_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_measurements.product_id->products.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_measurements" c JOIN "products" p ON p."id"=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_measurements.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_measurements" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_measurements.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_measurements" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_statements.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_statements" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'storage_statements.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "storage_statements" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'users.seller_id->sellers.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "users" c JOIN "sellers" p ON p."id"=c."seller_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'warehouse_boxes.inbound_request_id->inbound_intake_requests.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "warehouse_boxes" c JOIN "inbound_intake_requests" p ON p."id"=c."inbound_request_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'warehouse_boxes.pallet_id->pallets.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "warehouse_boxes" c JOIN "pallets" p ON p."id"=c."pallet_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'warehouse_boxes.storage_location_id->storage_locations.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "warehouse_boxes" c JOIN "storage_locations" p ON p."id"=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'warehouse_boxes.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "warehouse_boxes" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'warehouse_map_events.actor_user_id->users.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "warehouse_map_events" c JOIN "users" p ON p."id"=c."actor_user_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'warehouse_map_events.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "warehouse_map_events" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'warehouse_storage_racks.warehouse_id->warehouses.id' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE c.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "warehouse_storage_racks" c JOIN "warehouses" p ON p."id"=c."warehouse_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_lines: inbound_intake_requests->products' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_lines" c JOIN "inbound_intake_requests" r ON r.id=c."request_id" JOIN "products" p ON p.id=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_lines: inbound_intake_requests->storage_locations' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_lines" c JOIN "inbound_intake_requests" r ON r.id=c."request_id" JOIN "storage_locations" p ON p.id=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'outbound_shipment_lines: outbound_shipment_requests->products' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "outbound_shipment_lines" c JOIN "outbound_shipment_requests" r ON r.id=c."request_id" JOIN "products" p ON p.id=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'outbound_shipment_lines: outbound_shipment_requests->storage_locations' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "outbound_shipment_lines" c JOIN "outbound_shipment_requests" r ON r.id=c."request_id" JOIN "storage_locations" p ON p.id=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'marketplace_unload_lines: marketplace_unload_requests->products' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "marketplace_unload_lines" c JOIN "marketplace_unload_requests" r ON r.id=c."request_id" JOIN "products" p ON p.id=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_task_lines: packaging_tasks->products' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_task_lines" c JOIN "packaging_tasks" r ON r.id=c."task_id" JOIN "products" p ON p.id=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'packaging_task_lines: packaging_tasks->storage_locations' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "packaging_task_lines" c JOIN "packaging_tasks" r ON r.id=c."task_id" JOIN "storage_locations" p ON p.id=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_count_lines: inventory_counts->products' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_count_lines" c JOIN "inventory_counts" r ON r.id=c."count_id" JOIN "products" p ON p.id=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inventory_count_lines: inventory_counts->storage_locations' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inventory_count_lines" c JOIN "inventory_counts" r ON r.id=c."count_id" JOIN "storage_locations" p ON p.id=c."storage_location_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'discrepancy_act_lines: discrepancy_acts->products' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "discrepancy_act_lines" c JOIN "discrepancy_acts" r ON r.id=c."act_id" JOIN "products" p ON p.id=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_box_lines: inbound_intake_boxes->products' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_box_lines" c JOIN "inbound_intake_boxes" r ON r.id=c."box_id" JOIN "products" p ON p.id=c."product_id";
COMMIT;
BEGIN READ ONLY;
SET LOCAL statement_timeout = '5s';
SET LOCAL lock_timeout = '1s';
SELECT 'inbound_intake_cargo_place_lines: inbound_intake_cargo_places->products' AS relation, count(*) AS linked_rows, count(*) FILTER (WHERE r.tenant_id IS DISTINCT FROM p.tenant_id) AS tenant_mismatches FROM "inbound_intake_cargo_place_lines" c JOIN "inbound_intake_cargo_places" r ON r.id=c."cargo_place_id" JOIN "products" p ON p.id=c."product_id";
COMMIT;
