"""Generate physical-box barcodes accepted by Wildberries packaging uploads."""

from __future__ import annotations

import re
import secrets
import uuid

_CROCKFORD_BASE32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
_WB_BOX_BARCODE_PATTERN = re.compile(r"^[A-Za-z0-9_-]{6,30}$")
_ALLOWED_PREFIXES = frozenset({"WHB", "INB"})
_SUFFIX_LENGTH = 14
_SUFFIX_BITS = _SUFFIX_LENGTH * 5


def is_wb_compatible_box_barcode(value: str) -> bool:
    """Return whether *value* satisfies WB's self-generated box-code rules."""
    return bool(
        _WB_BOX_BARCODE_PATTERN.fullmatch(value)
        and not value.upper().startswith("WB_")
    )


_GENERATED_BOX_BARCODE_PATTERNS = {
    prefix: re.compile(rf"^{prefix}-[{_CROCKFORD_BASE32}]{{{_SUFFIX_LENGTH}}}$")
    for prefix in _ALLOWED_PREFIXES
}

# Before this module existed, InboundIntakeBox.internal_barcode was generated by
# inbound_intake_box_service._new_barcode() as f"INB-{uuid.uuid4().hex[:12].upper()}"
# (commit a9cebe6b). That shape is still live on production for boxes created
# before the switch to generate_box_barcode("INB"), e.g. 113 of the 408 current
# "Империя ФФ" boxes — it must count as system-generated too, not as a real
# external client code.
_LEGACY_GENERATED_INBOUND_BOX_BARCODE_PATTERN = re.compile(r"^INB-[0-9A-F]{12}$")


def is_generated_box_barcode(value: str, prefix: str) -> bool:
    """Return whether *value* matches a known generated shape for *prefix*.

    Unlike a plain prefix check, this also validates the random suffix so a
    lookalike external code (e.g. a client barcode that happens to start with
    the same prefix) is never mistaken for a system-generated one. Covers both
    the current generate_box_barcode() shape and, for INB, the legacy shape it
    replaced (see the note above).
    """
    normalized_prefix = prefix.upper()
    pattern = _GENERATED_BOX_BARCODE_PATTERNS.get(normalized_prefix)
    if pattern and pattern.fullmatch(value):
        return True
    return normalized_prefix == "INB" and bool(
        _LEGACY_GENERATED_INBOUND_BOX_BARCODE_PATTERN.fullmatch(value)
    )


# WMS-565: подпись «КР-00000N» / «Короб № N» для системного кода нужна только
# «Империи ФФ» — на её коробах наклеены бумажные «Короб 1», «Короб 2» (WMS-564).
# Остальные, например ArtMaks, клеят этикетку с самим кодом и ищут короб по нему.
NUMBERED_INBOUND_BOX_LABEL_TENANTS = frozenset(
    {uuid.UUID("7b98a8aa-c03c-4649-9677-a645be45c622")}
)


def uses_numbered_inbound_box_labels(tenant_id: uuid.UUID) -> bool:
    return tenant_id in NUMBERED_INBOUND_BOX_LABEL_TENANTS


def inbound_box_display_code(tenant_id: uuid.UUID, box_number: int, internal_barcode: str) -> str:
    if uses_numbered_inbound_box_labels(tenant_id) and is_generated_box_barcode(
        internal_barcode, "INB"
    ):
        return f"КР-{box_number:06d}"
    return internal_barcode


def generate_box_barcode(prefix: str) -> str:
    """Return a WB-compatible Code 128 value with 70 random bits.

    Fourteen Base32 symbols keep the complete value at 18 characters.  That
    length remains readable on the default 58x40 mm label at 203 dpi, unlike a
    maximum-length 30-character value, while retaining a negligible collision
    probability at WMS scale.
    """
    normalized_prefix = prefix.upper()
    if normalized_prefix not in _ALLOWED_PREFIXES:
        raise ValueError("WB-compatible generation is limited to WHB and INB boxes")

    suffix = _encode_number(secrets.randbits(_SUFFIX_BITS), _SUFFIX_LENGTH)
    barcode = f"{normalized_prefix}-{suffix}"
    if not is_wb_compatible_box_barcode(barcode):
        raise ValueError("generated box barcode is not WB-compatible")
    return barcode


def _encode_number(number: int, length: int) -> str:
    encoded = ["0"] * length
    for index in range(length - 1, -1, -1):
        encoded[index] = _CROCKFORD_BASE32[number & 31]
        number >>= 5
    return "".join(encoded)
