STATUS_DRAFT = "draft"
STATUS_SUBMITTED = "submitted"
STATUS_CONFIRMED = "confirmed"
STATUS_COLLECTING = "collecting"
STATUS_SHIPPED = "shipped"
STATUS_CANCELLED = "cancelled"

EXECUTION_STATUSES = (STATUS_CONFIRMED, STATUS_COLLECTING)
PACKAGING_SYNC_STATUSES = EXECUTION_STATUSES
RESERVE_STATUSES = (STATUS_SUBMITTED, STATUS_CONFIRMED, STATUS_COLLECTING)
CANCELLABLE_STATUSES = RESERVE_STATUSES
SELLER_EDITABLE_STATUSES = (STATUS_DRAFT,)
FF_LINE_EDITABLE_STATUSES = (STATUS_DRAFT, STATUS_CONFIRMED)
