import type { FbsWorkspace } from './fbsApi'
import projection from './wms673MarketplaceProjection.json'

// Default colors come from actual _map_order + FbsWorklistOrderOut projection
// generated by test_wms673_print_read_contract.py. Null/HTML inputs are edge cases.
// Synthetic API input. Real builders/components consume these records; no manually
// constructed new print-row color field is used to prove the data path.
export const WMS673_NOW = '2026-10-06T12:00:00Z'
export const WMS673_DEADLINE = '2026-10-07T12:00:00Z'
export const wms673Auth = () => ({ Authorization: 'Bearer synthetic-wms673' })
export function wms673Order(id: string, productId: string, color: string | null | undefined, tape = 0): FbsWorkspace['orders'][number] {
  return {
    id, marketplace: 'wb', external_order_id: null, wb_order_id: 673000 + tape,
    status: 'assembling', wb_status: 'confirm', supplier_status: 'confirm',
    seller: { id: 'seller-a', name: 'Синтетический селлер A' },
    wb_warehouse: { id: 507, name: 'Коледино' }, wms_warehouse: { id: 'wh-a', name: 'Тестовый склад' },
    product: { id: productId, name: `Товар ${productId}`, image_url: null,
      seller_article: `ART-${productId}`, wb_article: 1673, barcode: `WB-CODE-${productId}`,
      sku: `WB-SKU-${productId}`, chrt_id: 1, category: 'Одежда', color, size: '46', marketplace_bindings: [] },
    positions: [], inventory: { available_unpacked: 9, locations: [{ id: 'loc-a', code: 'A-01', available_unpacked: 9 }] },
    buyer_type: 'individual', cargo_type: 'mgt', can_pvz: false,
    metadata: { required: ['sgtin'], optional: [], states: [], delivery_allowed: false, last_checked_at: null },
    sticker: { code: `S673${String(tape).padStart(4, '0')}`, status: 'ready', asset_url: null, applied_at: null },
    pick: { status: 'pending', location_code: null, picked_at: null }, pack: { status: 'pending', packed_at: null },
    created_at_wb: WMS673_NOW, deadline_at: WMS673_DEADLINE, supply_id: 'supply-a', selection_blockers: [], tape_order_index: tape,
  } as unknown as FbsWorkspace['orders'][number]
}
export function wms673OzonOrder(): FbsWorkspace['orders'][number] {
  const one = wms673Order('oz-order', 'oz-red', 'Красный корня')
  return { ...one, marketplace: 'ozon', external_order_id: 'OZ-673-POSTING', wb_order_id: 867300,
    product: { ...one.product, name: 'Первая позиция Ozon', color: projection.ozon.product.color, barcode: projection.ozon.product.barcode, wb_article: null },
    positions: [
      { id: 'oz-pos-red', product_id: 'oz-red', name: 'Первая позиция Ozon', size: 'S', color: projection.ozon.positions[0].color,
        image_url: null, barcode: 'OZ-RED', seller_article: 'OZ-ART-RED', sku: '673101', quantity: 3, reserved_quantity: 3, picked_quantity: 1, marketplace_bindings: [{ marketplace: 'ozon', external_barcodes: ['OZ-RED'] }] },
      { id: 'oz-pos-blue', product_id: 'oz-blue', name: 'Вторая позиция Ozon', size: 'XL', color: projection.ozon.positions[1].color,
        image_url: null, barcode: 'OZ-BLUE', seller_article: 'OZ-ART-BLUE', sku: '673102', quantity: 2, reserved_quantity: 2, picked_quantity: 2, marketplace_bindings: [{ marketplace: 'ozon', external_barcodes: ['OZ-BLUE'] }] },
    ],
  } as unknown as FbsWorkspace['orders'][number]
}
export function wms673Workspace(id = 'supply-a', orders = [wms673Order('wb-red', 'red', projection.wb[0].color, 0), wms673Order('wb-blue', 'blue', projection.wb[1].color, 1)], marketplace: 'wb' | 'ozon' = 'wb'): FbsWorkspace {
  return {
    supply: { id, marketplace, wb_supply_id: marketplace === 'wb' ? `WB-GI-${id}` : null,
      external_supply_id: marketplace === 'ozon' ? 'OZ-SUPPLY-673' : null, source: 'wms', name: `FBS ${id}`,
      status: 'assembling', delivery_type: 'warehouse_sc', seller: { id: `seller-${id}`, name: `Синтетический селлер ${id}` },
      wb_warehouse: { id: 507, name: 'Коледино' }, wms_warehouse: { id: 'wh-a', name: 'Тестовый склад' },
      planned_destination: null, planned_shipment_date: null, nearest_deadline_at: WMS673_DEADLINE,
      packaging_task_id: null, barcode_asset: null },
    stage: 'composition', progress: { picked: 0, packed: 0, metadata_ready: 0, stickers_ready: 0, total: orders.length },
    blockers: [], orders, cargo_places: [], boxes: [], delivery_preflight: null, last_wb_sync_at: null, server_now: WMS673_NOW,
  } as unknown as FbsWorkspace
}
export const wms673PrintMeta = {
  supplyName: 'FBS synthetic WMS-673', wbSupplyId: 'WB-GI-SYNTHETIC-673', marketplace: 'wb' as const,
  sellerName: 'Синтетический селлер', wmsWarehouseName: 'Тестовый склад', routeLabel: 'Склад / СЦ',
  deadlineLabel: WMS673_DEADLINE, printedAtLabel: WMS673_NOW,
}
