"""inbound intake distribution lines

Revision ID: 126fb26be297
Revises: a06ee1327d13
Create Date: 2026-04-23 20:30:05.323060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126fb26be297'
down_revision: Union[str, Sequence[str], None] = 'a06ee1327d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_intake_distribution_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('storage_location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['inbound_intake_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_intake_distribution_lines_product_id'), 'inbound_intake_distribution_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_inbound_intake_distribution_lines_request_id'), 'inbound_intake_distribution_lines', ['request_id'], unique=False)
    op.create_index(op.f('ix_inbound_intake_distribution_lines_storage_location_id'), 'inbound_intake_distribution_lines', ['storage_location_id'], unique=False)
    op.add_column('inbound_intake_requests', sa.Column('distribution_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_intake_requests', 'distribution_completed_at')
    op.drop_index(op.f('ix_inbound_intake_distribution_lines_storage_location_id'), table_name='inbound_intake_distribution_lines')
    op.drop_index(op.f('ix_inbound_intake_distribution_lines_request_id'), table_name='inbound_intake_distribution_lines')
    op.drop_index(op.f('ix_inbound_intake_distribution_lines_product_id'), table_name='inbound_intake_distribution_lines')
    op.drop_table('inbound_intake_distribution_lines')
    # ### end Alembic commands ###
