-- candidate_summary
WITH c AS (SELECT l.*,o.seller_id order_seller_id,o.tenant_id order_tenant_id,o.product_id order_product_id,o.status,o.marketplace,o.supply_id,p.seller_id current_seller_id,p.tenant_id product_tenant_id,u.source supply_source,u.delivered_at FROM fbs_shipment_reversal_ledger l JOIN fbs_orders o ON o.id=l.fbs_order_id JOIN fbs_supplies u ON u.id=o.supply_id JOIN products p ON p.id=l.product_id WHERE p.seller_id IN ('d1f26146-e99a-41af-9471-9c80ec990db3','184f4b05-e623-4746-8edf-c5e408e6d026','a852f30d-bb63-42f9-ac7f-a701ee857cca') AND u.delivered_at IS NOT NULL AND o.status NOT IN ('cancelled','defect') AND l.reversed_at IS NULL AND l.shipment_movement_id IS NULL) SELECT s.name,t.name tenant,count(*) rows,sum(c.quantity) units,min(c.created_at) first_ledger,max(c.created_at) last_ledger,count(*) FILTER(WHERE c.current_seller_id<>c.order_seller_id OR c.tenant_id<>c.order_tenant_id OR c.tenant_id<>c.product_tenant_id OR c.order_product_id IS DISTINCT FROM c.product_id) mismatch,count(*) FILTER(WHERE c.supply_source<>'wms') not_wms,count(*) FILTER(WHERE c.marketplace<>'wb') not_wb,count(*) FILTER(WHERE c.container_id IS NOT NULL) container_rows,md5(string_agg(c.id::text,',' ORDER BY c.id)) candidate_ids_md5 FROM c JOIN sellers s ON s.id=c.current_seller_id JOIN tenants t ON t.id=c.tenant_id GROUP BY s.name,t.name ORDER BY s.name;

-- candidate_sources
WITH c AS (SELECT l.* FROM fbs_shipment_reversal_ledger l JOIN fbs_orders o ON o.id=l.fbs_order_id JOIN fbs_supplies u ON u.id=o.supply_id JOIN products p ON p.id=l.product_id WHERE p.seller_id IN ('d1f26146-e99a-41af-9471-9c80ec990db3','184f4b05-e623-4746-8edf-c5e408e6d026','a852f30d-bb63-42f9-ac7f-a701ee857cca') AND u.delivered_at IS NOT NULL AND o.status NOT IN ('cancelled','defect') AND l.reversed_at IS NULL AND l.shipment_movement_id IS NULL), g AS (SELECT tenant_id,product_id,storage_location_id,container_kind,container_id,sum(quantity) needed FROM c GROUP BY 1,2,3,4,5) SELECT s.name,count(*) source_groups,sum(g.needed) units,sum(coalesce(b.quantity,0)) physical_at_exact_source,count(*) FILTER(WHERE coalesce(b.quantity,0)<g.needed) insufficient_source_groups,sum(greatest(g.needed-coalesce(b.quantity,0),0)) shortage_units,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM inventory_movements m WHERE m.product_id=g.product_id AND m.movement_type='ownership_transfer_out')) products_with_ownership_out FROM g JOIN products p ON p.id=g.product_id JOIN sellers s ON s.id=p.seller_id LEFT JOIN inventory_balances b ON b.tenant_id=g.tenant_id AND b.product_id=g.product_id AND b.storage_location_id=g.storage_location_id AND b.container_kind IS NOT DISTINCT FROM g.container_kind AND b.container_id IS NOT DISTINCT FROM g.container_id GROUP BY s.name ORDER BY s.name;

-- billing_coverage
SELECT t.name,t.billing_enabled_from,(SELECT count(*) FROM billing_tariff_versions_v2 v WHERE v.tenant_id=t.id AND v.service_code IN ('fbs_order','packing')) all_v2_rates,(SELECT count(*) FROM billing_tariff_versions_v2 v WHERE v.tenant_id=t.id AND v.service_code IN ('fbs_order','packing') AND v.enabled AND v.valid_from_at<'2026-09-09' AND (v.valid_to_at IS NULL OR v.valid_to_at>='2026-08-01')) enabled_v2_rates_overlapping_aug_sep,(SELECT count(*) FROM billing_tariff_versions v WHERE v.tenant_id=t.id AND v.service_code IN ('fbs_order','packing')) legacy_rates FROM tenants t WHERE t.id='7b98a8aa-c03c-4649-9677-a645be45c622';

-- mashnin_negative
SELECT p.id product_id,l.storage_location_id,count(*) candidate_orders,sum(l.quantity) candidate_units,b.quantity current_physical,b.quantity-sum(l.quantity) after_proposed_writeoff FROM fbs_shipment_reversal_ledger l JOIN fbs_orders o ON o.id=l.fbs_order_id JOIN fbs_supplies u ON u.id=o.supply_id JOIN products p ON p.id=l.product_id LEFT JOIN inventory_balances b ON b.tenant_id=l.tenant_id AND b.product_id=l.product_id AND b.storage_location_id=l.storage_location_id AND b.container_kind IS NOT DISTINCT FROM l.container_kind AND b.container_id IS NOT DISTINCT FROM l.container_id WHERE p.seller_id='184f4b05-e623-4746-8edf-c5e408e6d026' AND u.delivered_at IS NOT NULL AND o.status NOT IN ('cancelled','defect') AND l.reversed_at IS NULL AND l.shipment_movement_id IS NULL GROUP BY p.id,l.storage_location_id,b.quantity HAVING coalesce(b.quantity,0)<sum(l.quantity);
